#!/bin/bash
# NixOS like configuration file based system manager for Void Linux

# Default values
packages=()
auth="sudo"

execute () {
  echo "The system has been rebuilt!"
}

execute_once () {
  echo "The system has been built!"
}

# Load the configuration file
. $HOME/.config/config.void

# Check if the authenticator is installed on the system
which "$auth" 2>/dev/null >/dev/null || auth=sudo

# Rebuild the system and manage packages
rebuild() {
  eval $auth xbps-install -y ${packages[@]} || exit 1

  installed_pkgs=$(xbps-query -m | sed 's/^\([^ ]*\)-.*/\1/')
  to_remove=()

  # Find out the unneeded packages
  for package in ${installed_pkgs[@]}; do

    if [[ ! " ${packages[@]} " =~ " $package " ]]; then

      # Some packages must not be removed
      case "$package" in
        "base-system") ;;
        "grub"*) ;;
        *) to_remove+=( "$package" ) ;;
      esac

    fi

  done

  # Get rid of unneeded packages
  [ ${#to_remove[@]} -gt 0 ] && {
    eval $auth xbps-remove -Ry ${to_remove[@]} || exit 1
  }

  # Post rebuild execution hook
  execute

  # Setup optional auto login for user
  if [ -z "$autologin" ]; then
    $auth sed -i "s/GETTY_ARGS=.*$/GETTY_ARGS=''/g" /etc/sv/agetty-tty1/conf
  else
    getent passwd "$autologin" >/dev/null
    $auth sed -i "s/GETTY_ARGS=.*$/GETTY_ARGS='--autologin $autologin'/g" /etc/sv/agetty-tty1/conf
  fi
}

# Build the system, meant to be used only ONCE
build() {
  rebuild
  execute_once

  exit 0
}

# Help
help() {
  blue='[34m'
  yellow='[33m'
  green='[32m'
  normal='[0m'
  progname="$(echo $0 | sed 's|.*/||g' | tr '[:lower:]' '[:upper:]')"

  printf "$blue$progname$normal - NixOS inspired system management in Void Linux.\n
${blue}SYNTAX$normal
  ${green}${0##*/} ${yellow}OPTION$normal\n\n${blue}AVAILABLE OPTIONS$normal\n"

  printf "  ${green}rebuild$normal Rebuild the system.
   • Install the packages listed in ${yellow}'packages'$normal.
   • Remove unlisted manually installed packages (${green}\`xbps-query --list-manual-pkgs\`$normal)
   • Run the ${yellow}'execute'$normal function.
   • If ${yellow}'auth'$normal is a valid authenticator, use that as ${yellow}'\$auth'$normal.
   • If ${yellow}'autologin'$normal is non-blank, autologin for that user in ${green}\`tty1\`$normal.\n\n"

  printf "  ${green}build$normal Build the system, only to be used once.
   • Run ${green}'rebuild'$normal.
   • Run the ${yellow}'execute_once'$normal function.\n\n"

  printf "If no options are supplied, assume ${green}'rebuild'$normal to be the option.\n"

  exit 0
}

# Build/rebuild (depends) void if no arguments specified
# If an arguments is supplied, do that action
if [ -z $1 ]; then
  rebuild
else
  type=$(LC_ALL=C type -t $1 2>/dev/null)
  if [ ! -z "$type" ] && [ "$type" = "function" ]; then
    $1
  else
    printf "Unknown option [33m'$1'[0m
    See [32m\`${0##*/} help\`[0m for more information.\n"

    exit 127
  fi

  exit 0
fi
